<?php
module_load_include('inc', 'social_icons', 'includes/social_icons.block');

/**
 * Implements hook_menu().
 */
function social_icons_menu() {
  $items['admin/config/administration/social-icon'] = array(
    'title' => t('Social Icons'),
    'description' => t('Setting social icons'),
    'page callback' => 'social_icons_list',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/administration/social-icon/list'] = array(
    'title' => t('Social Icons List'),
    'description' => t('List social icons'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
  );
  $items['admin/config/administration/social-icon/add'] = array(
    'title' => t('Add Social Icons'),
    'description' => t('Setting social icons'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('social_icons_setting_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
   // 'file' => 'inc/social_icons_edit.inc',
    'weight' => 1,
  );
  $items['admin/config/administration/social-icon/%social_icons/edit'] = array(
    'title' => t('Edit Social Icons'),
    'description' => t('Setting social icons'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('social_icons_setting_form', 4),
    'access arguments' => array('administer site configuration'),
    //'file' => 'inc/social_icons_edit.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/config/administration/social-icon/%social_icons/delete'] = array(
    'title' => t('Delete Social Icons'),
    'description' => t('Setting social icons'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('social_icons_delete_form', 4),
    'access arguments' => array('administer site configuration'),
    //'file' => 'inc/social_icons_edit.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}


/**
 * Implements hook_entity_info()
 */
function social_icons_entity_info() {
  return array(
    'social_icons' => array(                               // Системное имя сущности
      'label' => t('Social icons'),
      // Человеко-понятное имя сущности
      'entity class' => 'Entity',
      // Класс сущности
      'controller class' => 'EntityAPIController',
      // Контроллер сущности
      'base table' => 'social_icons',
      // Таблица, в которой хранится информация об альбомах
      'entity keys' => array(
        'id' => 'id',
        // Название поля, в котором распологаются идентификаторы альбомов
        'label' => 'title'
        // Название поля, в котором распологаются названия альбомов
      ),
      'admin ui' => array(
        'path' => 'admin/config/administration/social-icon'
        // Путь, по которому будет доступна админка
      ),
      'access callback' => 'social_icons_access',
      // Имя функции, отвечающей за проверку прав доступа
      'module' => 'social_icons',
    ),
  );
}

/**
 * Проверка прав доступа
 */
function social_icons_access($op, $entity, $account = NULL, $entity_type = 'social_icons') {
  return user_access('administer site configuration'); // сущность будет доступна только администратору сайта
}

/**
 * Возвращает альбом по его идентификатору
 */
function social_icons_load($id) {
  $result = entity_load('social_icons', array($id));
  return $result ? reset($result) : FALSE;
}

/**
 * Function return array for theme_image()
 * @param $fid - fid of files
 *
 */
function _image_array($fid) {
  return array(
    'path' => file_load($fid)->uri,
    'width' => '50px',
    'height' => '50px',
    'attributes' => array('class' => 'some-img', 'id' => 'my-img'),
  );
}

/**
 * Realisation function social_icons_list()
 * Callback icon list
 */
function social_icons_list() {
  $social_icons = db_select('social_icons', 'si')
    ->fields('si', array('id'))
    ->orderBy('si.id')
    ->execute();
  $header = array(t('Title'), t('Link'), t('Icon'), t('Hover Icon'), t('Actions'));
  $rows = array();

  foreach ($social_icons as $id) {
    $entity = social_icons_load($id->id);
    $actions = array(
      l(t('edit'), 'admin/config/administration/social-icon/' . $id->id . '/edit'),
      l(t('delete'), 'admin/config/administration/social-icon/' . $id->id . '/delete', array('query' => array('token' => drupal_get_token('social_icons-' . $id->id)))),
    );
    $rows[] = array(
      $entity->title,
      $entity->link,
      theme_image(_image_array($entity->icon)),
      theme_image(_image_array($entity->hover_icon)),
      implode(' | ', $actions)
    );
  }
  $output = theme('table', array('header' => $header, 'rows' => $rows));

  return $output;
}

/**
 * Implements hook_form()
 */
function social_icons_setting_form($form, &$form_state, $social_icons = NULL, $op = 'edit') {
  // $arg = is_numeric(arg(4)) ? arg(4) : NULL;
//  $social_icons = isset($arg) ? social_icons_load(arg(4)) : '';

  $form['setting'] = array(
    '#title' => t('Add icon'),
    '#type' => 'fieldset',
  );
  $form['setting']['id'] = array(
    '#type' => 'value',
    '#value' => isset($social_icons->id) ?  $social_icons->id : FALSE,
  );
  $form['setting']['title'] = array(
    '#title' => t('Title'),
    '#type' => 'textfield',
    '#maxlength' => 64,
    '#size' => 60,
    '#required' => TRUE,
    '#attributes' => array('class' => array('title')),
    '#default_value' => isset($social_icons->title) ? $social_icons->title : '',
  );
  $form['setting']['link'] = array(
    '#title' => t('Link'),
    '#type' => 'textfield',
    '#maxlength' => 124,
    '#required' => TRUE,
    '#atributes' => array('class' => array('link')),
    '#description' => t('Input link in format "http://" or "https://".'),
    '#default_value' => isset($social_icons->link) ? $social_icons->link : '',
  );
  $form['setting']['icon'] = array(
    '#title' => t('Upload icon'),
    '#type' => 'managed_file',
    '#default_value' => isset($social_icons->icon) ? $social_icons->icon : '',

    //  '#required' => TRUE,

  );
  $form['setting']['hover_icon'] = array(
    '#title' => t('Upload hover icon'),
    '#type' => 'managed_file',
    '#default_value' => isset($social_icons->hover_icon) ? $social_icons->hover_icon : '',

    //  '#required' => TRUE,

  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit')
  );
  return $form;
}

/**
 * Implements hook_forms_validate().
 */
function social_icons_setting_form_validate($form, $form_state) {

  if (!preg_match('/^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$/', $form_state['values']['link'])) {
    form_set_error('link', t('"Link" do not begin "http://" or "https://".'));
  }

  $validators = array(
    'file_validate_is_image' => array(), // Проверка, действительно ли файл является изображением
    // 'file_validate_extensions' => array('png gif jpg jpeg'), // Проверка на расширения
    //'file_validate_size' => array(1 * 1024 * 1024), // Проверка на размер файла (максимум 1mb)
  );
  $icon = file_save_upload('icon', $validators);
  // if ($icon = file_move($icon, 'public://')) {
  // Save the file for use in the submit handler.
  // $form_state['values']['icon'] = $icon;
  // }
  $hover_icon = file_save_upload('hover_icon', $validators);
  $form_state['values']['hover_icon'] = $hover_icon;

  // Загружаем файл в sites/default/files (по умолчанию)
//  if ($file = file_save_upload('icon', $validators, 'public://')) {
//    $form_state['values']['icon'] = $file; // передаём информацию о файле в ф-ю social_icons_setting_form_submit()
//  }
//  else {
//    form_set_error('icon', 'Файл не был загружен');
//  }
}

/**
 * Implements hook_form_submit()
 */
function social_icons_setting_form_submit($form, &$form_state) {
  // загружем основную иконку
  $icon = file_load($form_state['values']['icon']);
  // $icon->status = 1;
  $icon = file_save($icon);
  if ($form_state['values']['id']) {
    $social_icons = social_icons_load($form_state['values']['id']);
    $social_icons->title = $form_state['values']['title'];
    $social_icons->link = $form_state['values']['link'];
    $social_icons->icon = $form_state['values']['icon'];
    $social_icons->hover_icon = $form_state['values']['hover_icon'];
    $social_icons = entity_save('social_icons', $social_icons);
  } else {
    $values = array(
      'title' => $form_state['values']['title'],
      'link' => $form_state['values']['link'],
      'icon' => $form_state['values']['icon'],
      'hover_icon' => $form_state['values']['hover_icon'],
    );
    $social_icons = entity_create('social_icons', $values);
    $social_icons = entity_save('social_icons', $social_icons);

  }
  if ($social_icons) {
    drupal_set_message(t('Form submit'));
  }
  $form_state['redirect'] = 'admin/config/administration/social-icon/list';
}

/**
 * Realised delete entity
 */
function social_icons_delete_form($form, &$form_state, $social_icons) {
//  if (!drupal_valid_token($_GET['token'], 'social_icons-' . $social_icons->id)) {
//    return drupal_access_denied();
//  }
  $form['delete']= array(
    '#title' => t('Delete Icons'),
    '#type' => 'fieldset',
  );
  $form['id'] = array(
    '#type' => 'value',
    '#value' => $social_icons->id
  );
  $form['delete']['back'] = array(
    '#type' => 'markup',
    '#markup' => l(t('Return back'), 'admin/config/administration/social-icon/list')
  );
  $form['delete']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Delete'),
    '#submit' => array('social_icon_delete_form_submit'),
    // '#validate' => TRUE,

  );
  return $form;
}

/**
 * Function delete entity social_icons
 */
function social_icon_delete_form_submit($form, &$form_state) {
  $delete = entity_delete('social_icons', $form_state['values']['id']);
  if ($delete) {
    drupal_set_message(t('Icons delete'));
  }
  $form_state['redirect'] = 'admin/config/administration/social-icon/list';


}